name: Update Point Comment
on:
  issues:
    types: [edited]

jobs:
  update_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if point changed
        id: check_point
        uses: actions/github-script@v5  # Đã cập nhật từ v4 sang v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const issue = payload.issue;
            const changes = payload.changes;

            // Log payload và issue
            console.log('Payload:', payload);
            console.log('Issue:', issue);
            
            // Check if the issue was edited and if the point field was changed
            if (changes && 'point' in changes) {
              const oldPoint = changes['point'].from;
              const newPoint = changes['point'].to;
              return {
                pointChanged: true,
                oldPoint: oldPoint,
                newPoint: newPoint
              };
            } else {
              return {
                pointChanged: false
              };
            }

      - name: Update issue comment
        if: steps.check_point.outputs.pointChanged == 'true'
        uses: actions/github-script@v5  # Đã cập nhật từ v4 sang v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const oldPoint = '${{ steps.check_point.outputs.oldPoint }}';
            const newPoint = '${{ steps.check_point.outputs.newPoint }}';
            const commentBody = `adjustmode1 updated point from ${oldPoint} to ${newPoint}.`;
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });