name: Log Point Field Update in Project
on:
  project:
    types: [moved, closed]

jobs:
  log_point_update:
    runs-on: ubuntu-latest
    steps:
      - name: Check if point field updated in project
        id: check_point_update
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            console.log("payload: ",JSON.stringtify(payload, null, 2))
            
            // Check if this is a project move event
            if (payload.action !== 'moved') {
              return { pointFieldUpdated: false };
            }
            
            const projectCard = payload.project_card;
            const contentURL = projectCard.content_url;

            // Get the issue associated with the project card
            const issueResponse = await github.request('GET /repos/{owner}/{repo}/issues', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              headers: {
                Accept: 'application/vnd.github.v3+json',
              },
              params: {
                state: 'all',
                per_page: 1,
                url: contentURL
              }
            });

            console.log("point: ",JSON.stringtify(issueResponse, null, 2))

            const issue = issueResponse.data[0];
            const pointField = 'point'; // Update this if your field name is different

            // Check if 'point' field updated in the issue
            const hasPointFieldUpdated = 'changes' in issue && pointField in issue.changes;

            return { pointFieldUpdated: hasPointFieldUpdated };

      - name: Log point field update in project
        if: steps.check_point_update.outputs.pointFieldUpdated == true
        run: |
          echo "Point field has been updated in the project associated with the issue."