name: Multi-Event Trigger

on:
  issues:
    types: 
      - edited
      - transferred
  project:
    types: 
      - edited
  project_card:
    types: 
      - edited
  project_column:
    types: 
      - edited

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "hello--------------------------------------------------"
