name: Milestone Update

on:
  issues:
    types: [milestoned]

jobs:
  comment_on_update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get issue information
        id: issue_info
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          mediaType: |
            previews:
              - symmetra

      - name: Post a comment with the milestone update
        uses: actions/github-script@v6
        with:
          script: |
            const oldMilestone = "old_value"; // Cần thay thế giá trị này bằng cách lưu trữ thông tin trước đó
            const newMilestone = "${{ github.event.issue.milestone.title }}";
            const issueNumber = ${{ github.event.issue.number }};
            const comment = `Milestone custom field changed from "${oldMilestone}" to "${newMilestone}"`;

            await github.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: comment
            });
