name: Log Point Changes

on:
  issues:
    types: [edited]

jobs:
  log_point_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log Point Changes
        if: github.event.issue.fields.point != null && github.event.changes.point != null
        run: |
          echo "Issue ${ISSUE_NUMBER} point changed from ${OLD_POINT} to ${NEW_POINT}"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OLD_POINT: ${{ github.event.changes.point.from }}
          NEW_POINT: ${{ github.event.changes.point.to }}